parameters:

    #
    # Factories
    #
    elcodi.factory.configuration.class: Elcodi\Component\Configuration\Factory\ConfigurationFactory

    #
    # Services
    #
    elcodi.manager.configuration.class: Elcodi\Component\Configuration\Services\ConfigurationManager

    #
    # Twig extensions
    #
    elcodi.twig_extension.configuration.class: Elcodi\Component\Configuration\Twig\ConfigurationExtension

    #
    # Commands
    #
    elcodi.command.configuration_set.class: Elcodi\Component\Configuration\Command\ConfigurationSetCommand
    elcodi.command.configuration_get.class: Elcodi\Component\Configuration\Command\ConfigurationGetCommand
    elcodi.command.configuration_delete.class: Elcodi\Component\Configuration\Command\ConfigurationDeleteCommand
