services:

    #
    # Commands
    #
    elcodi.command.configuration_set:
        class: %elcodi.command.configuration_set.class%
        arguments:
            template_loader: @elcodi.manager.configuration
        tags:
            -  { name: console.command }

    elcodi.command.configuration_get:
        class: %elcodi.command.configuration_get.class%
        arguments:
            template_loader: @elcodi.manager.configuration
        tags:
            -  { name: console.command }

    elcodi.command.configuration_delete:
        class: %elcodi.command.configuration_delete.class%
        arguments:
            template_loader: @elcodi.manager.configuration
        tags:
            -  { name: console.command }
