services:

    #
    # Commands
    #
    elcodi.configuration_set_command:
        class: %elcodi.configuration_set_command.class%
        arguments:
            - @elcodi.manager.configuration
        tags:
            -  { name: console.command }

    elcodi.configuration_get_command:
        class: %elcodi.configuration_get_command.class%
        arguments:
            - @elcodi.manager.configuration
        tags:
            -  { name: console.command }

    elcodi.configuration_delete_command:
        class: %elcodi.configuration_delete_command.class%
        arguments:
            - @elcodi.manager.configuration
        tags:
            -  { name: console.command }
