services:

    #
    # Object Managers
    #
    elcodi.object_manager.configuration:
        parent: elcodi.abstract_manager
        arguments: [ %elcodi.core.configuration.entity.configuration.class% ]
