services:

    #
    # Repositories
    #

    #
    # Repository for entity configuration
    #
    elcodi.repository.configuration:
        parent: elcodi.abstract_repository
        arguments: [ %elcodi.core.configuration.entity.configuration.class% ]
