services:

    #
    # Twig extensions
    #
    elcodi.twig_extension.configuration:
        class: %elcodi.twig_extension.configuration.class%
        arguments:
            - @elcodi.manager.configuration
        tags:
            - { name: twig.extension }
